spring.datasource.url=jdbc:postgresql://ep-little-poetry-apt2u1m6-pooler.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9DTIocJrOj0V
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
management.endpoints.web.exposure.include=health,info,metrics
